sot_controller:
  libname: libsot-tiago-steel-controller.so
  joint_names: [  torso_lift_joint,
    arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint,
    gripper_finger_joint,
    head_1_joint, head_2_joint ]
  map_rc_to_sot_device: { motor-angles: motor-angles ,
  joint-angles: joint-angles, velocities: velocities, forces: forces, currents: currents,
  torques: torques, cmd-joints: control, cmd-effort: control, accelerometer_0: accelerometer_0, gyrometer_0: gyrometer_0 }
  position_control_init_pos:
    - name: torso_lift_joint
      des_pos: 0.0
    - name: arm_1_joint
      des_pos: 0.25847
    - name: arm_2_joint
      des_pos: 0.173046
    - name: arm_3_joint
      des_pos: 0.0002
    - name: arm_4_joint
      des_pos: -0.525366
    - name: arm_5_joint
      des_pos: 0.0
    - name: arm_6_joint
      des_pos: 0.0
    - name: arm_7_joint
      des_pos: 0.1
    - name: gripper_finger_joint
      des_pos: 0.034
    - name: head_1_joint
      des_pos: 0.0
    - name: head_2_joint
      des_pos: 0.0   
  control_mode: POSITION
  dt: 0.001
  jitter: 0.0004
  
